Loft App gets its own directory
ucsb-cs148-s21/t7-local-network-file-transfer pull request #35
Opened 2021-04-25 13:01 UTC by at527

- creates and uses a dedicated folder for loft functions
- doesn't touch user's downloads folder (I noticed it overwriting a file with the same name that I previously uploaded for testing)
- adds ~/loftApp/received and ~/loftApp/send

- Simplifies issue #33 (show uploaded files), just show files in ~/loftApp/received
- Simplifies issue #14 (show files being served), just display files in ~/loftApp/send
- maybe we can symlink files selected to be sent into the send folder

To test, perform upload and navigate to ~/loftApp/received

closes #34

2021-04-26 03:26 UTC, ethwu commented
Looks good, but I'd suggest we use `~/Loft` or `~/Documents/Loft` since that's probably friendlier from a user point of view (or at least `~/loft`, since it's not likely for there to be a "loft" that isn't an app).

2021-04-26 03:30 UTC, ethwu requested changes
For the sake of symmetry, I also think it might be better if the folders are `SEND_FOLDER` and `RECEIVE_FOLDER`.

Also, I think there's an `os.makedirs` which can make a whole filepath with intermediate folders, which might be useful.

2021-04-26 07:22 UTC, at527 commented
> For the sake of symmetry, I also think it might be better if the folders are `SEND_FOLDER` and `RECEIVE_FOLDER`.
I debated this for a bit and thought received made sense since these are the files the user "received". Does look kind of funny so I'll change it.
 
> Also, I think there's an `os.makedirs` which can make a whole filepath with intermediate folders, which might be useful.
Will implement

2021-04-26 07:31 UTC, at527 commented
> Looks good, but I'd suggest we use `~/Loft` or `~/Documents/Loft` since that's probably friendlier from a user point of view (or at least `~/loft`, since it's not likely for there to be a "loft" that isn't an app).

I had it as loftApp so I could differentiate it from my files own more easily. Not very pretty though so I'll change it to just ~/Loft. I'm a little wary of putting things into the documents file, but it's probably more accessible for Windows users.

2021-04-26 23:53 UTC, ethwu commented
We could also do a check for if the OS is Windows, and if so use `~/Documents/Loft` instead of `~/Loft`. For some reason Windows is like allergic to having user folders in the home directory, so everything gets lumped into `~/Documents` instead.

Now I think about it, we could borrow email terminology and use `Loft/Inbox` and `Loft/Outbox`, which sidesteps the tense thing with `send` and `received`. What do you think?

2021-04-27 02:22 UTC, zmondin reviewed
Everything works and I was able to find the folders. With that being said, I think we should change where the folder winds up because I initially had to search for it. I managed to find it under Users/ZackM (in my case) but maybe storing it in the documents file, like Ethan suggested, would be best so people can find it easier. Or maybe include instructions on where to find the folder based on your OS. Otherwise, it looks good to me!

2021-04-27 23:28 UTC, at527 commented
Revert to using Downloads folder. No need for creating a file in the user's directory.

2021-04-27 23:28 UTC, closed without merging